// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherProject.Infrastructure.Data;

#nullable disable

namespace WeatherProject.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeatherProject.Core.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Timezone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Country")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Egypt",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Latitude = 30.0444m,
                            Longitude = 31.2357m,
                            Name = "Cairo",
                            Timezone = "Africa/Cairo"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Egypt",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Latitude = 31.2001m,
                            Longitude = 29.9187m,
                            Name = "Alexandria",
                            Timezone = "Africa/Cairo"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Egypt",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Latitude = 29.9870m,
                            Longitude = 31.2118m,
                            Name = "Giza",
                            Timezone = "Africa/Cairo"
                        });
                });

            modelBuilder.Entity("WeatherProject.Core.Entities.WeatherCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("WeatherConditions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "clear",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clear sky",
                            Icon = "01d"
                        },
                        new
                        {
                            Id = 2,
                            Code = "clouds",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cloudy",
                            Icon = "04d"
                        },
                        new
                        {
                            Id = 3,
                            Code = "rain",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rain",
                            Icon = "10d"
                        },
                        new
                        {
                            Id = 4,
                            Code = "snow",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Snow",
                            Icon = "13d"
                        },
                        new
                        {
                            Id = 5,
                            Code = "thunderstorm",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thunderstorm",
                            Icon = "11d"
                        },
                        new
                        {
                            Id = 6,
                            Code = "mist",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mist",
                            Icon = "50d"
                        });
                });

            modelBuilder.Entity("WeatherProject.Core.Entities.WeatherData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("FeelsLike")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Humidity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Precipitation")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Pressure")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeatherConditionId")
                        .HasColumnType("int");

                    b.Property<int>("WindDirection")
                        .HasColumnType("int");

                    b.Property<decimal>("WindSpeed")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("WeatherConditionId");

                    b.HasIndex("CityId", "Timestamp")
                        .IsUnique();

                    b.ToTable("WeatherData");
                });

            modelBuilder.Entity("WeatherProject.Core.Entities.WeatherData", b =>
                {
                    b.HasOne("WeatherProject.Core.Entities.City", "City")
                        .WithMany("WeatherRecords")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WeatherProject.Core.Entities.WeatherCondition", "WeatherCondition")
                        .WithMany("WeatherRecords")
                        .HasForeignKey("WeatherConditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("WeatherCondition");
                });

            modelBuilder.Entity("WeatherProject.Core.Entities.City", b =>
                {
                    b.Navigation("WeatherRecords");
                });

            modelBuilder.Entity("WeatherProject.Core.Entities.WeatherCondition", b =>
                {
                    b.Navigation("WeatherRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
